name: "Godot Export"
on: [push, workflow_dispatch]

env:
  GODOT_VERSION: 3.3.2
  PROJECT_NAME: Noumenon
  PROJECT_PATH: noumenon
  EXPORT_MODE: debug # If not defined, defaults to debug
  # Required if in release mode
  # K8S_SECRET_RELEASE_KEYSTORE_BASE64: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_BASE64 }}
  # K8S_SECRET_RELEASE_KEYSTORE_USER: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_USER }}
  # K8S_SECRET_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_PASSWORD }}
  # IOS_ICON_PATH: "noumenon/icon.png"
  ITCH_GAME: noumenon
  ITCH_USER: robruana

jobs:
  export:
    name: "Godot Export"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux, MacOS, Windows, HTML5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Export Godot Project
      - name: Export ${{ matrix.platform }} Version
        id: export
        uses: vini-guerrero/godot-exporter/actions/export@master
        with:
          platform: ${{ matrix.platform }}

      # Publish Platforms
      # - name: Publish Platforms
      #   uses: vini-guerrero/godot-exporter/actions/publish@master
      #   with:
      #     platform: "Itch"
      #     channel: ${{ matrix.platform }}
      #     project_path: ${{ steps.export.outputs.artifact-path }}

      # Upload Artifact
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}
          path: ${{ steps.export.outputs.artifact-path }}
